### PR TITLE
Lots of code change for very little actual change

### PR DESCRIPTION
**Pull request by samsouder**
Mostly a re-org and bundle affair for fun. Added some new synonyms that I thought humorous and made the font more spiffy.

See if it's to your liking or if I've hurt load performance too much: https://goodjobteam-kwto28hc4.now.sh

### CODE REVIEW

**Comment by samsouder** [comment]
Just checked this morning and my css changes have made the all-important mobile experience worse. I’ll fix that up.

**Comment by samsouder** [comment]
Updated version much happier on differing screen sizes: https://goodjobteam-juqxn6ca6.now.sh

**Comment by sburba** [comment]
I don't know how to PR to your PR, but this makes the build work:

git diff HEAD^
diff --git a/.nowignore b/.nowignore
new file mode 100644
index 0000000..293fab6
--- /dev/null
+++ b/.nowignore
@@ -0,0 +1,6 @@
+node_modules
+dist
+.idea
+.cache
+.editorconfig
+
diff --git a/now.json b/now.json
index 633d541..fe3b131 100644
--- a/now.json
+++ b/now.json
@@ -4,12 +4,8 @@
   "alias": ["gooodjob.team"],
   "builds": [
     {
-      "src": "dist/*",
-      "use": "@now/static"
+     "src": "package.json",
+     "use": "@now/static-build"
     }
-  ],
-  "routes": [
-    { "src": "/", "dest": "dist/index.html" },
-    { "src": "/(.*)", "dest": "dist/$1" }
   ]
 }
diff --git a/package.json b/package.json
index 66e0138..c98588c 100644
--- a/package.json
+++ b/package.json
@@ -3,7 +3,8 @@
   "version": "1.0.0",
   "scripts": {
     "start": "parcel index.html --open",
-    "build": "parcel build index.html"
+   "now-build": "yarn run build"
   },
   "license": "MIT",
   "dependencies": {

**Comment by samsouder** [comment]
Didn't see the @now/static-build package, nice. All done.

**Pull request merged**
